type: object
required:
  - _id
  - name
  - price
  - category
  - description
  - userId
properties:
  _id:
    description: "Product's id"
    type: string
    example: 65e4decdd286b30065d54af9
  name:
    description: "Product's name"
    type: string
    example: 'Coffee'
  price:
    description: "Product's price"
    type: number
    example: 12
  category:
    description: "Product's category"
    type: string
    enum: ['books', 'electronics', 'clothing', 'other']
  description:
    description: "Product's description"
    type: string
    example: Lavazza
  userId:
    description: "Product's userId id"
    type: string
    example: 65e4decdd286b30065d54af9
  createdAt:
    description: 'Created at'
    type: number
    example: 02/03/2025
  updatedAt:
    description: 'Updated at'
    type: number
    example: 02/03/2025
